# Generated by Django 5.2.4 on 2025-08-03 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='dislike_count',
            new_name='dislikes',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='like_count',
            new_name='likes',
        ),
    ]
